# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# cross check CI

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/target/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
- task: Bash@3
  displayName: Move WAR to Root
  inputs:
    targetType: 'inline'
    script: 
      mv $(Build.ArtifactStagingDirectory)/*.war $(Build.SourcesDirectory)
- task: Docker@2
  displayName: Build and push Docker Image
  inputs:
    containerRegistry: 'acr-service-conn'
    repository: 'warapp-image'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 
      latest
- task: AzureWebAppContainer@1
  displayName: Deploy Container to WebApp
  inputs:
    azureSubscription: 'azure-conn'
    appName: 'warappbhanu123'
    containers: 'bhanuacr123.azurecr.io/warapp-image:latest'



    

